### PR TITLE
Swift 3.0 and Xcode 8 GM support

### PR DESCRIPTION
**Pull request by fedetrim**
Forked from @pascalfribi's PR https://github.com/matthewpalmer/Locksmith/pull/140. 
Added a Test Host target with Keychain Sharing capabilities.

Also, added @aaronpearce's suggestion to change `old[String(kSecReturnData)] = true` to `old[String(kSecReturnData)] = kCFBooleanTrue` in `asReadableSecureStoragePropertyDictionary`.

Tests are passing in my machine, running Xcode 8 GM.

### CODE REVIEW

**Comment by fedetrim** [comment]
Some Travis test configurations are failing. I will need some help with .travis.yml
Never used Travis before so I'm having issues there. Tests are passing in my machine.

**Comment by phatmann** [comment]
Xcode 8 is out! Time to merge this PR.

**Comment by matthewpalmer** [comment]
Yep, will work on this when I have time on the weekend 👍

**Comment by mohpor** [comment]
@fedetrim could you add `-verbos` flag to `xcodebuild` commands in `.travis.yml` file?
It should look like: `xcodebuild -verbose -workspace ....` this way we might be able to solve the Travis problem.

Thanks.

P.S.: I'm very thankful for this great library and I know @matthewpalmer  is busy during week, but my projects won't build and that means I have to wait a few days to be able to work on them! I simply cannot wait that long.

**Comment by matthewpalmer** [comment]
Merged—thanks so much @fedetrim!
I'll dig into travis soon 👍

**Comment by pascalfribi** [comment]
Thanks for merging @matthewpalmer ! I am very thankful for this library!

**Comment by esetnik** [comment]
thanks @fedetrim

**Pull request merged**
