### PR TITLE
Fix new Xcode 9 warnings, update to Swift 4

### PR DESCRIPTION
**Pull request by emaloney**
• Fixed a redundant conformance constraint warning
• Updated settings as per suggestions from Xcode 9
• set APPLICATION_EXTENSION_API_ONLY to NO for unit tests (this setting is only needed for Locksmith itself)
• Updated to Swift 4 (which only required changes to the unit tests; the core Locksmith is Swift 4 compliant out-of-the-box)

### CODE REVIEW

**Comment by clayellis** [comment]
@matthewpalmer Please approve this PR quickly 🤞🏻

**Comment by emaloney** [comment]
I can take a stab at fixing the Travis issues if that's a requirement for consideration of this pull request. Unfortunately, Travis has been seriously messed up over the last few days (at least as far as their macOS infrastructure is concerned). In fact, I just checked now and [the Travis CI status page is down](https://www.traviscistatus.com).

**Comment by phillfarrugia** [comment]
@emaloney can you try updating the travis.yml to `osx_image: xcode9`?

**Comment by matthewpalmer** [comment]
Thanks @emaloney and everyone! Sorry for the delay on my end 👍. Let me know if there are any other issues, I should have time in the next week to look into it.

(P.S. @emaloney I've added you as a collaborator to Locksmith 💥)

**Pull request merged**
