### PR TITLE
Converted to Swift 1.2

### PR DESCRIPTION
**Pull request by ChaosCoder**
Code support now Swift 1.2 syntax.

### CODE REVIEW

**Comment by matthewpalmer** [comment]
Thanks! Will merge this in once when Xcode 6.3 gets closer to release.

**Comment by Arcrammer** [comment]
Holy cow that must have been a lot of work!

**Comment by nunogoncalves** [comment]
@matthewpalmer can this be merged, since swift 1.2 is out of beta now? :)

**Comment by barnybug** [comment]
+1 for merging now, please

**Pull request merged**
