### PR TITLE
Update for Xcode 8 beta 6

### PR DESCRIPTION
**Pull request by JeromeTan1997**

### CODE REVIEW

**Comment by devloomax** [comment]
If anyone has an idea to get this to work on beta 6, would be great :)
I wanted to start beta-testing with Testflight with my beta 5 app, but beta 5 builds are not accepted anymore by Itunes Connect.

**Comment by pascalfribi** [comment]
I have been working on the same thing as well. Instead of adding casts to AnyObject I have changed the Dictionaries to be of type [String: Any] which is now the standard Dictionary type when working with Id from Objective-C. This removes the need for casts to AnyObject.

I have also modified the tests and they pass on OS X, but not on iOS. Any idea why?

**Comment by JeromeTan1997** [comment]
You should run the tests on a real device rather than a simulator, it's something to do with the Keychain service itself.

**Comment by pascalfribi** [comment]
Hi Jerome,

How can I run the test suites on a real device? When I want to do that XCode tells me: "Logic testing on iOS devices is not supported. You can run logic tests on the Simulator."

What about changing your pull request to redefine the [String: AnyObject] dictionary definitions to [String: Any]? As far as I understood, this is the new way Apple wants us to treat Dictionaries in conjunction with Objective-C libraries. They are of type [AnyHashable: Any] to be more specific.

This seems the proper solution to me, then you can remove your type casts to AnyObject.

What do you think?

**Comment by JeromeTan1997** [comment]
To run tests on devices needs a host app, otherwise the tests probably won't ever pass until Apple fixes it.

Since you've already done the modification, I think it's a better idea to submit your pull request.

**Comment by pascalfribi** [comment]
I can do that. But do you also think this is the better approach? I am no swift expert and I need to doublecheck my understanding a bit :-)

**Comment by matthewpalmer** [comment]
This has been merged in #142. Thanks very much @JeromeTan1997 :)

**Pull request closed without merging**
