### PR TITLE
Keychain enumeration

### PR DESCRIPTION
**Pull request by getaaron**
### Unfinished — Do Not Merge

This PR addresses https://github.com/matthewpalmer/Locksmith/issues/45.

This code…

- Adds a static array of security classes
- Implements `each(userAccount:, itemHandler)` by iterating through the classes and calling the handler when appropriate
- Deprecates `.Many` and replaces it with `.All`
- Makes `userAccount` optional

This enables two types of iteration possible. One with a user account:

    Locksmith.each("foo@bar.com") { result in
        print(result)
    }
    
And one without:

    Locksmith.each() { result in
        print(result)
    }

`SecItemCopyMatching` will return an array, not a dictionary, if `kSecMatchLimit != 1`. But `performRequest(_:)` only handles a single dictionary return value at the moment. So I think that will need to be updated as well.

Still to do:

- Test on an app with real-world data
- Handle arrays in `performRequest(_:)`

Bonus points:

- In the Swift 2.0 branch, use `SequenceType` and `CollectionType` protocols to make an enumerable type. This would enable developers to filter results, get counts, iterate in reverse, etc.

@matthewpalmer I'm adding you as a collaborator on my fork so you can push directly to this branch if you want. Anyone else interested, let me know.

### CODE REVIEW

**Comment by matthewpalmer** [comment]
@getaaron this looks awesome! Thanks so much for all your work contributing to Locksmith 👍

Had a look at building on what you've started, and I had a super annoying time with builds/running tests/etc. Don't think this is a new issue (i.e. you definitely didn't introduce it), but it makes working on Locksmith way harder. Have you found any work arounds for it?

Otherwise I might spend a bit of time improving the ease-of-development (no idea what that'll take), and then I'll keep working on this. Would be keen to hear your thoughts/complaints too :)

**Comment by getaaron** [comment]
@matthewpalmer What specific issues are you having? I didn't have any.

**Comment by matthewpalmer** [comment]
#52 is a pretty big rewrite/redesign and will soon be merged into master. I really like this idea and want to include, but haven’t had a chance to introduce it into #52 yet. You’re welcome to bring it into that branch (reopen this PR if so), or I’ll do it once the new API settles in a bit.

Thanks again for your help :)

**Comment by victor** [comment]
What's the status of this branch?
It'd definitely be useful to be able to list all known accounts for a given service (or for all services). Most keychain wrappers I've seen (except Sam Soffes') assume you know the user account name, so clients of these libraries need to store them elsewhere, typically in NSUserDefaults.
But Keychain itself allows for querying for the full list, which makes more sense IMHO, for apps that allow you to use more than one account (such as a Twitter client, for example) and allow the user to choose without they providing the account name.

thanks

**Comment by getaaron** [comment]
@victor I think we all agree it's a nice idea and none of us have gotten around to finishing it

**Comment by zilions** [comment]
Any updates on this?

**Comment by getaaron** [comment]
No updates on my end, feel free to take over if you want to wrap it up.

**Pull request closed without merging**
