### PR TITLE
+ Updates to the new Swift 2 syntax

### PR DESCRIPTION
**Pull request by SirWellington**
+ Updates under the new Swift Exception Handling `try` `do` `catch` scheme is still needed.
+ Unit test cases passed

### CODE REVIEW

**Comment by matthewpalmer** [comment]
Thanks! Will merge in these changes when I do a couple of other improvements related to Swift 2 (hopefully within a week or two) 👍

**Comment by SirWellington** [comment]
You got it! I'll let you take care of it. If you need help with the improvements let me know. Otherwise, looking forward to it.

**Comment by matthewpalmer** [comment]
@SirWellington added these changes to a new branch (`2.0`) which will get merged into master down the track. Thanks for your help!

**Comment by matthewpalmer** [comment]
This has been used in #52, which will be merged into master soon. Thanks again for your help!

**Pull request closed without merging**
